language: generic

os: osx
osx_image: xcode7.3

env:
  global:
    - CONDA_PY=27
    - MINICONDA_FILE="Miniconda2-4.6.14-MacOSX-x86_64.sh"
  matrix:
    - build_scrt="build_recipe.sh"
    - build_scrt="build_no_recipe.sh"


before_install:
    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


script:
  - bash ci_support/${build_scrt}
