version: 2

jobs:
  build_no_recipe:
    docker:
      - image: circleci/buildpack-deps:16.04
    steps:
      - run: sudo apt-get update && sudo apt-get install freeglut3-dev
      - checkout
      - restore_cache:
          keys:
            - mini-eman-deps-15.0-1
      - save_cache:
          key: mini-eman-deps-15.0-1
          paths:
            - ~/miniconda2
      - run: bash ci_support/build_no_recipe.sh

  build_recipe:
    docker:
      - image: circleci/buildpack-deps:16.04
    steps:
      - run: sudo apt-get update && sudo apt-get install freeglut3-dev
      - checkout
      - restore_cache:
          keys:
            - mini-eman-deps-15.0-1
      - save_cache:
          key: mini-eman-deps-15.0-1
          paths:
            - ~/miniconda2
      - run: bash ci_support/build_recipe.sh

workflows:
  version: 2
  build_recipe_and_no_recipe:
    jobs:
      - build_no_recipe
      - build_recipe
