version: 2

jobs:
  build_no_recipe:
    docker:
      - image: circleci/buildpack-deps:16.04
    steps:
      - run: sudo apt-get update && sudo apt-get install freeglut3-dev
      - run:
          command: |
            sudo apt-get install build-essential software-properties-common -y
            sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
            sudo apt-get -q update -y
            sudo apt-get -q install gcc-5 g++-5 -y
            sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 1 --slave /usr/bin/g++ g++ /usr/bin/g++-5
      - checkout
      - restore_cache:
          keys:
            - mini-eman-deps-16.0-boost=1.64-1
      - save_cache:
          key: mini-eman-deps-16.0-boost=1.64-1
          paths:
            - ~/miniconda2
      - run: bash ci_support/build_no_recipe.sh

  build_recipe:
    docker:
      - image: circleci/buildpack-deps:16.04
    steps:
      - run: sudo apt-get update && sudo apt-get install freeglut3-dev
      - run:
          command: |
            sudo apt-get install build-essential software-properties-common -y
            sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
            sudo apt-get -q update -y
            sudo apt-get -q install gcc-5 g++-5 -y
            sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 1 --slave /usr/bin/g++ g++ /usr/bin/g++-5
      - checkout
      - restore_cache:
          keys:
            - mini-eman-deps-16.0-boost=1.64-1
      - save_cache:
          key: mini-eman-deps-16.0-boost=1.64-1
          paths:
            - ~/miniconda2
      - run: bash ci_support/build_recipe.sh

workflows:
  version: 2
  build_recipe_and_no_recipe:
    jobs:
      - build_no_recipe
      - build_recipe
